# Generated by Django 4.2.3 on 2023-07-08 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_post_image_image_post_imagess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='imagess',
            new_name='Images',
        ),
    ]
