# Generated by Django 4.2.3 on 2023-07-08 22:08

from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_rename_imagess_post_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Images',
        ),
        migrations.AddField(
            model_name='post',
            name='project_url',
            field=models.URLField(default='https://example.com'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=events.models.upload_to),
        ),
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_images', to='events.post'),
        ),
    ]
