# Generated by Django 4.2.3 on 2023-07-10 00:15

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='project_url',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=events.models.upload_to),
        ),
    ]
