# Generated by Django 4.2.3 on 2023-07-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_post_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='added_by',
        ),
        migrations.AddField(
            model_name='post',
            name='project_url',
            field=models.URLField(default='https://example.com'),
        ),
    ]
