# Generated by Django 4.2.3 on 2023-07-10 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_remove_post_added_by_post_project_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='project_url',
        ),
    ]
