# Generated by Django 4.2.3 on 2023-07-10 22:34

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_remove_post_project_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.CharField(choices=[('books', 'Books'), ('book_chapters', 'Book Chapters'), ('refereed_articles', 'Refereed Articles'), ('conference_papers', 'Conference Papers'), ('phd_thesis', 'PhD Thesis'), ('master_thesis', 'Master Thesis'), ('other_publications', 'Other Publications')], max_length=200)),
                ('authors', models.CharField(max_length=200, null=True)),
                ('place', models.CharField(max_length=200, null=True)),
                ('publication_date', models.DateField(null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=events.models.upload_to)),
            ],
        ),
    ]
