# Generated by Django 4.2.3 on 2023-07-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='links',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_link',
            field=models.URLField(blank=True),
        ),
    ]
