# Generated by Django 4.2.3 on 2023-07-18 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0020_article_links_article_title_article_title_link'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='post',
            name='project_url',
            field=models.URLField(default='https://example.com'),
        ),
        migrations.AlterField(
            model_name='article',
            name='links',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
