# Generated by Django 4.2.3 on 2023-07-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_article_article_type_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='bibtex',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.IntegerField(null=True),
        ),
    ]
