# Generated by Django 4.2.3 on 2023-07-21 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0023_article_bibtex_alter_article_place_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='project_date',
            new_name='event_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='presentation',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='client',
        ),
        migrations.RemoveField(
            model_name='post',
            name='project_url',
        ),
        migrations.AddField(
            model_name='post',
            name='program_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_program_images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
