# Generated by Django 4.2.3 on 2023-07-21 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_post_speacker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='speacker',
            new_name='speaker',
        ),
    ]
