# Generated by Django 4.2.3 on 2023-07-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_rename_speacker_post_speaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='place',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_link',
        ),
        migrations.AlterField(
            model_name='article',
            name='publication_date',
            field=models.IntegerField(null=True),
        ),
    ]
